### ISSUE TITLE
[CLOSED] Move Entity models into database

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#1015]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Saturday Oct 09, 2021 at 11:29 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/956_

----

## 🍰 Pullrequest

This PR moves the entities into the database project and references entities in the backend with `@entity/* ` imports. Furthermore entity models are now also handled according to their migration so we have a history of all entities in every migration.

This is the first step for the upcomming seeding mechanism which will be implemented in the database project. I want to use https://github.com/w3tecch/typeorm-seeding which in turn requires us to have typeorm available in the database including all models.

### Issues

- relates #178
- relates #774

### Todo

- [X] None

@Mogge This has several problems from my point of view:
- The `@entity` path is defined three times: In the jest.config, in the tsconfig.json and the package.json. The jest config could be ommited if we remove all comments from the tsconfig(not compliant with strict json parsing) - i thought this would be a bad idea. The thing in the package.json is required to have it running when built(also possible removable when the tsconfig.json would be a valid json) and the tsconfig.json which is the actual real thing
- The content in the backend docker needs to be the whole project. This makes the context bigger, and therefore increases build time. On the workflow is has a very marginal effect; On my local machine is has an increased build time. This could be optimized with some smart dockerignore files and definitions.
- This entangles both projects backend and database closely into each other. While the code is separated and clearly two things, the compiled backend will include parts of the database. Furthermore the backend will not be buildable without database.

The advantages of this is the clear separation of models from the business logic. The database definitions are where they should be. All old models are also available in database and backend and there is a single source of truth for those. The models are defined where they are changed as well (migrations).

Is this cool? Worth it? Too complex? Are we missing the actual goal when the two project parts get so closely entangled?

----

_**[ulfgebhardt](https://github.com/ulfgebhardt)** included the following code: https://github.com/gradido/gradido/pull/956/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Monday Oct 11, 2021 at 23:30 GMT_

----

> I get this error:
> 
> ```
> backend_1           | TSError: ⨯ Unable to compile TypeScript:
> backend_1           | src/typeorm/getDBVersion.ts(1,27): error TS2307: Cannot find module '@entity/Migration' or its corresponding type declarations.
> backend_1           | 
> backend_1           |     at createTSError (/app/node_modules/ts-node/src/index.ts:587:12)
> ```

I believe it shall work now - i fixed several errors in database connection & docker setup. Please try. Consider a `--build` or even `docker system prune -a` if still not working

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Tuesday Oct 12, 2021 at 11:54 GMT_

----

```
 Error: Cannot find module 'reflect-metadata'
database_1          | Require stack:
database_1          | - /app/src/index.ts
database_1          |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
```

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Tuesday Oct 12, 2021 at 11:54 GMT_

----

```
backend_1           | Error: Cannot find module '/database/build/entity/index'
backend_1           | Require stack:
backend_1           | - /app/src/typeorm/connection.ts
backend_1           | - /app/src/index.ts
backend_1           |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
```

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/ulfgebhardt"><img src="https://avatars.githubusercontent.com/u/1238238?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ulfgebhardt](https://github.com/ulfgebhardt)**
_Tuesday Oct 19, 2021 at 22:26 GMT_

----

@Mogge Another test pls - we were so close ;)

`docker-compose up --build`
