### ISSUE TITLE
[CLOSED] refactor(backend): no email in user

### ISSUE THREAD

**Issue by ulfgebhardt** [Zahlungsmittel/Zahlungsmittel#3012]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Mogge](https://github.com/Mogge)**
_Tuesday Apr 18, 2023 at 14:27 GMT_
_Originally opened as https://github.com/gradido/gradido/pull/2953_

----

## 🍰 Pullrequest
Remove email data from User graphql object

### Issues
- relates #2952
-->
- None

### Todo

- [X] None

----

_**[Mogge](https://github.com/Mogge)** included the following code: https://github.com/gradido/gradido/pull/2953/commits_

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mahula](https://github.com/mahula)**
_Tuesday Apr 18, 2023 at 16:06 GMT_

----

Good work so far.
The end-to-end tests fail for this frontend-related reason:
Logging in does not work - the frontend-side requests gets the response 

> `{"errors":[{"message":"Cannot query field \"email\" on type \"User\".","locations":[{"line":4,"column":5}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Cannot query field \"email\" on type \"User\".","    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:48:31)","    at Object.enter (/app/node_modules/graphql/language/visitor.js:323:29)","    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:370:25)","    at visit (/app/node_modules/graphql/language/visitor.js:243:26)","    at Object.validate (/app/node_modules/graphql/validation/validate.js:69:24)","    at validate (/app/node_modules/apollo-server-core/src/requestPipeline.ts:536:14)","    at Object.<anonymous> (/app/node_modules/apollo-server-core/src/requestPipeline.ts:302:32)","    at Generator.next (<anonymous>)","    at fulfilled (/app/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)","    at processTicksAndRejections (node:internal/process/task_queues:95:5)"]}}}]}
> `

The login request in the frontend needs some adaptation, too.

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/Mogge"><img src="https://avatars.githubusercontent.com/u/15882241?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Mogge](https://github.com/Mogge)**
_Tuesday Apr 18, 2023 at 16:16 GMT_

----

@mahula Thanks. I need to merge #2952 first

**Comment by ulfgebhardt** [comment]
<a href="https://github.com/mahula"><img src="https://avatars.githubusercontent.com/u/3883288?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mahula](https://github.com/mahula)**
_Tuesday Apr 18, 2023 at 18:45 GMT_

----

> @mahula Thanks. I need to merge #2952 first

#2952 has been approved.
